import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageDir = dirname(scriptDir);
const packageJsonPath = join(packageDir, 'package.json');
const versionFilePath = join(packageDir, 'src', 'version.ts');

const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));

if (!packageJson.version || typeof packageJson.version !== 'string') {
  throw new Error(`Missing or invalid version in ${packageJsonPath}`);
}

const nextContent = `// Generated by packages/core/scripts/generate-version.mjs\nexport const SHOWRUN_VERSION = '${packageJson.version}';\n`;
writeFileSync(versionFilePath, nextContent, 'utf-8');
